import esbuild from "esbuild";
import builtins from "builtin-modules";

const production = process.argv[2] === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Source: packages/obsidian-chart in the tufte monorepo.
*/`;

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  // obsidian, electron, and node builtins are provided by the runtime and must
  // stay external. @tufte/chart-core is intentionally NOT external so the
  // artifact is self-contained.
  external: ["obsidian", "electron", ...builtins],
  format: "cjs",
  target: "es2018",
  platform: "node",
  bundle: true,
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  minify: production,
  outfile: "main.js",
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
