// Builds the self-hosted, npm-independent ESM bundle of @tufte/chart-core
// that tufte.ai serves off GitHub Pages.
//
// Because core is zero-dependency pure ESM, we can bundle it into a single
// minified file and serve it from the deploy root. `app/public/` is copied to
// the Pages root, so app/public/chart-core@<version>.js -> https://tufte.ai/chart-core@<version>.js
//
// Writes two files:
//   - chart-core@<version>.js  (immutable, pinned to this version)
//   - chart-core.js            (latest convenience alias)

import { build } from "esbuild";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..", "..");
const corePkgPath = resolve(repoRoot, "packages/core/package.json");
const coreEntry = resolve(repoRoot, "packages/core/src/index.js");
const outDir = resolve(__dirname, "..", "public");

const pkg = JSON.parse(await readFile(corePkgPath, "utf8"));
const { name, version } = pkg;

const banner = `/*! ${name}@${version} — self-hosted ESM build (https://tufte.ai). Generated by app/scripts/build-cdn.mjs; do not edit by hand. */`;

const outputs = [
  resolve(outDir, `chart-core@${version}.js`),
  resolve(outDir, `chart-core.js`),
];

for (const outfile of outputs) {
  await build({
    entryPoints: [coreEntry],
    outfile,
    bundle: true,
    format: "esm",
    platform: "neutral",
    minify: true,
    banner: { js: banner },
  });
  console.log(`build-cdn: wrote ${outfile}`);
}

console.log(`build-cdn: bundled ${name}@${version} (${outputs.length} files)`);
